spring:
  application:
    name: fillWordFileBot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/fill_word_file_bot?currentSchema=public
      username: postgres
      password: local
bot:
  name: fillWordFileBot
  token: 7582447684:AAEctTa5RR8q3Nh-iD9ekzRoC7JXK34Scbw
